# Generated by scripts/check-spec.mjs from Starling's OpenAPI security requirements.
SIGNED_ROUTES = [
    {
        "method": "PUT",
        "path": "/api/v2/account-holder/individual/email"
    },
    {
        "method": "POST",
        "path": "/api/v2/addresses"
    },
    {
        "method": "PUT",
        "path": "/api/v2/payments/local/account/{accountUid}/category/{categoryUid}/standing-orders/{paymentOrderUid}"
    },
    {
        "method": "DELETE",
        "path": "/api/v2/payments/local/account/{accountUid}/category/{categoryUid}/standing-orders/{paymentOrderUid}"
    },
    {
        "method": "PUT",
        "path": "/api/v2/payments/local/account/{accountUid}/category/{categoryUid}/standing-orders"
    },
    {
        "method": "PUT",
        "path": "/api/v2/payments/local/account/{accountUid}/category/{categoryUid}"
    }
]
